### ISSUE TITLE
adds kernel source of this Japanese variant SC-02L,A530D

### ISSUE THREAD

**Issue by hdk2d** [MacBookPro34-comma-7/android_kernel_samsung_universal7885#1]
this is the only A8 2018 variant that was upgraded to stock android 10 
this is my telegram user for testing purposes https://t.me/DarkHerman94
![Screenshot 2022-07-27 at 17-26-36 Samsung Open Source](https://user-images.githubusercontent.com/86883038/181385528-93d6065e-cd60-4fcc-8d44-e7025b82315c.png)

**Comment by hurrhnn** [comment]
Work In Progress, Please check your telegram account.
